"use client"

import Link from "next/link"
import { useActionState, useState, useEffect } from "react"
import { signup, signInWithGoogle } from "@/actions/auth"

const features = [
  {
    icon: "📚",
    title: "AI Study Plans",
    desc: "Personalized roadmaps generated by our neural engine based on your curriculum.",
  },
  {
    icon: "📊",
    title: "Real-time Progress",
    desc: "Visual analytics that track your cognitive load and retention rates as you study.",
  },
  {
    icon: "🔔",
    title: "Smart Reminders",
    desc: "Adaptive alerts timed perfectly to match your peak focus hours.",
  },
]

export default function SignupPage() {
  const [state, formAction, isPending] = useActionState(signup, { error: "" })
  const [showBubble, setShowBubble] = useState(true)

  useEffect(() => {
    const handleClick = () => setShowBubble(false)
    document.addEventListener("click", handleClick)
    return () => document.removeEventListener("click", handleClick)
  }, [])

  return (
    <div className="flex h-screen w-full overflow-hidden bg-[#f7f9fb]">


      {/* ── Left Panel: Feature Teaser ────────────────────────── */}
      <div className="hidden lg:flex flex-col justify-between w-1/2 bg-[#f2f4f6] p-16 h-full relative overflow-hidden">
        {/* Decorative orb */}
        <div className="absolute -top-24 -left-24 w-96 h-96 rounded-full opacity-40 blur-3xl pointer-events-none" style={{ background: "#00685f15" }} />

        <div className="relative z-10">
          {/* Logo */}
          <div className="flex items-center gap-3 mb-20">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center text-white text-lg"
              style={{ background: "linear-gradient(135deg, #00685f, #008378)" }}
            >
              🧠
            </div>
            <span className="text-xl font-bold tracking-tight" style={{ color: "#00685f" }}>
              NeuroPlan AI
            </span>
          </div>

          <div className="max-w-md">
            <p className="text-[11px] font-bold tracking-[0.1em] uppercase mb-3" style={{ color: "#00685f" }}>
              The Cognitive Atelier
            </p>
            <h1 className="text-4xl font-extrabold tracking-tight text-[#191c1e] mb-12 leading-[1.1]">
              Design your path to academic mastery.
            </h1>

            <div className="space-y-8">
              {features.map((f) => (
                <div key={f.title} className="flex items-start gap-4">
                  <div className="w-12 h-12 rounded-xl bg-[#e6e8ea] flex items-center justify-center text-xl shrink-0">
                    {f.icon}
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-[#191c1e]">{f.title}</h3>
                    <p className="text-sm text-[#3d4947] leading-relaxed">{f.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Social proof removed per user request */}
      </div>

      {/* ── Right Panel: Signup Form ──────────────────────────── */}
      <div className="w-full lg:w-1/2 flex flex-col items-center justify-center px-8 lg:px-24 py-12 bg-white h-full overflow-y-auto">
        <div className="w-full max-w-sm">

          {/* Mobile logo */}
          <div className="lg:hidden flex items-center gap-3 mb-12">
            <div
              className="w-9 h-9 rounded-xl flex items-center justify-center text-white"
              style={{ background: "linear-gradient(135deg, #00685f, #008378)" }}
            >
              🧠
            </div>
            <span className="text-lg font-bold tracking-tight" style={{ color: "#00685f" }}>NeuroPlan AI</span>
          </div>

          <header className="mb-10">
            <h2 className="text-3xl font-bold tracking-tight text-[#191c1e] mb-1">Create Account</h2>
            <p className="text-sm text-[#3d4947]">Start your journey toward focused learning.</p>
          </header>

          <form action={formAction} className="space-y-5">
            {state?.error && (
              <div className="px-4 py-3 rounded-xl bg-red-50 border border-red-200 text-red-600 text-sm font-medium">
                {state.error}
              </div>
            )}

            {/* Full Name */}
            <div>
              <label className="block text-[11px] font-bold tracking-[0.05em] text-[#3d4947] uppercase mb-2" htmlFor="name">
                Full Name
              </label>
              <div className="input-underline">
                <input
                  id="name"
                  name="name"
                  type="text"
                  placeholder="Alex Sterling"
                  required
                  className="w-full px-4 py-3.5 bg-[#f2f4f6] rounded-lg border-none text-sm text-[#191c1e] placeholder:text-[#bcc9c6] outline-none transition-all focus:bg-white"
                />
              </div>
            </div>

            {/* Email */}
            <div>
              <label className="block text-[11px] font-bold tracking-[0.05em] text-[#3d4947] uppercase mb-2" htmlFor="email">
                Email Address
              </label>
              <div className="input-underline">
                <input
                  id="email"
                  name="email"
                  type="email"
                  placeholder="alex@university.edu"
                  required
                  className="w-full px-4 py-3.5 bg-[#f2f4f6] rounded-lg border-none text-sm text-[#191c1e] placeholder:text-[#bcc9c6] outline-none transition-all focus:bg-white"
                />
              </div>
            </div>

            {/* Password */}
            <div>
              <label className="block text-[11px] font-bold tracking-[0.05em] text-[#3d4947] uppercase mb-2" htmlFor="password">
                Password
              </label>
              <div className="input-underline">
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="••••••••"
                  required
                  className="w-full px-4 py-3.5 bg-[#f2f4f6] rounded-lg border-none text-sm text-[#191c1e] placeholder:text-[#bcc9c6] outline-none transition-all focus:bg-white"
                />
              </div>
            </div>

            {/* Terms */}
            <div className="flex items-center gap-3 py-1">
              <input
                id="terms"
                type="checkbox"
                required
                className="w-4 h-4 rounded border-[#bcc9c6] accent-[#00685f]"
              />
              <label htmlFor="terms" className="text-sm text-[#3d4947]">
                I agree to the{" "}
                <a href="#" className="font-medium hover:underline" style={{ color: "#00685f" }}>Terms of Service</a>
                {" "}and{" "}
                <a href="#" className="font-medium hover:underline" style={{ color: "#00685f" }}>Privacy Policy</a>.
              </label>
            </div>

            {/* Submit */}
            <button
              type="submit"
              disabled={isPending}
              className="w-full py-4 rounded-xl text-white font-bold text-sm tracking-wide shadow-lg active:scale-[0.98] hover:scale-[1.01] transition-all disabled:opacity-60"
              style={{ background: "linear-gradient(135deg, #00685f, #008378)", boxShadow: "0 4px 20px rgba(0,104,95,0.25)" }}
            >
              {isPending ? "Creating Account..." : "Create Account"}
            </button>
          </form>

          {/* Social + Login link */}
          <div className="mt-8 flex flex-col items-center gap-6">
            <div className="flex items-center gap-4 w-full">
              <div className="h-px bg-[#e2e8f0] flex-grow" />
              <span className="text-[11px] font-bold text-[#6d7a77] uppercase tracking-wider">Or continue with</span>
              <div className="h-px bg-[#e2e8f0] flex-grow" />
            </div>

            <div className="grid grid-cols-2 gap-4 w-full">
              <button
                type="button"
                onClick={() => signInWithGoogle()}
                className="flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-[#f2f4f6] hover:bg-[#e6e8ea] transition-colors"
              >
                <svg className="w-4 h-4" viewBox="0 0 24 24">
                  <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
                  <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-1.01.68-2.33 1.09-3.71 1.09-2.85 0-5.27-1.92-6.13-4.51H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
                  <path d="M5.87 14.15c-.22-.68-.35-1.41-.35-2.15s.13-1.47.35-2.15V7.01H2.18C1.43 8.52 1 10.21 1 12s.43 3.48 1.18 4.99l3.69-2.84z" fill="#FBBC05" />
                  <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.01l3.69 2.84c.86-2.59 3.28-4.51 6.13-4.47z" fill="#EA4335" />
                </svg>
                <span className="text-sm font-semibold text-[#191c1e]">Google</span>
              </button>
              <button
                type="button"
                className="flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-[#f2f4f6] hover:bg-[#e6e8ea] transition-colors"
              >
                <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" />
                </svg>
                <span className="text-sm font-semibold text-[#191c1e]">GitHub</span>
              </button>
            </div>

            <p className="text-sm text-[#3d4947]">
              Already have an account?{" "}
              <Link href="/login" className="font-bold hover:underline" style={{ color: "#00685f" }}>
                Sign In
              </Link>
            </p>
          </div>

          <footer className="mt-16 text-center">
            <p className="text-[10px] font-bold text-[#bcc9c6] uppercase tracking-[0.2em]">
              NeuroPlan AI — The Cognitive Atelier © 2024
            </p>
          </footer>
        </div>

        {/* AI Assistant Bubble */}
        <div 
          onClick={(e) => e.stopPropagation()}
          className={`fixed bottom-8 right-8 z-50 transition-all duration-500 transform ${
            showBubble ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4 pointer-events-none"
          }`}
        >
          <div className="bg-white/80 backdrop-blur-xl p-4 rounded-2xl shadow-2xl flex items-start gap-3 max-w-xs border border-[#e2e8f0]">
            <div
              className="w-10 h-10 rounded-full flex items-center justify-center shrink-0 text-lg"
              style={{ background: "linear-gradient(135deg, #00685f, #008378)" }}
            >
              ✨
            </div>
            <div className="text-[12px] leading-tight">
              <span className="font-bold block mb-1" style={{ color: "#00685f" }}>AI Assistant</span>
              <p className="text-[#3d4947]">Complete your profile to unlock custom neural pathways.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
